### ISSUE TITLE
modules and commands 

### ISSUE THREAD

**Issue by sid050603** [tanmay606/YouTubeMusicPythonAPI#1]
can you send me the modules and commands which we need to install for this project.

**Comment by tanmay606** [comment]
You only need selenium library, which you can install directly by using pip functionality which comes with python,
type : pip install selenium .

**Comment by tanmay606** [comment]
and for runtime commands :

 	        2.) =forward  : Move Current Video Backward ,For Specific Time (=forward:time in sec EG: =forward:35)
	        3.) =backward : Move Current Video Backward, For Specific Time (=forward:time in sec EG: =backward:35)
	        4.) =restart : It Will Restart The Current Video.
	        5.) =pause : It Will Pause The Current Video.
	        6.) =play : It Will Play The Pause Video.
	        7.) =refresh : It Will Refresh The Page.
	        8.) =quit : Closes The Program.
	        9.) =? / =HELP / =help : Help.
